version: '2'
services:
  web:
    build: .
    ports:
      - 1337:1337
    environment:
      SESSION_SECRET: THISISMEANCOFFEESTARTER
      MONGODB: mongodb://mongo:27017/mcs
      REDISHOST: redis
      REDISPORT: 6379
  redis:
    image: 'redis:3.2'
  mongo:
    image: 'mongo:3.4'