version: '2'
services:
  client:
    build: ./client
    volumes:
      - ./client:/usr/src/app
    command: "sh -c 'yarn && yarn run dev'"
    ports:
      - 1338:1338
  server:
    build: ./server
    volumes:
      - ./server:/usr/src/app
    command: "sh -c 'yarn && npm run dev'"
    ports:
      - 1337:1337
    environment:
      PORT: 1337
      SESSION_SECRET: THISISSPANSTARTER
      MONGODB: mongodb://mongo:27017/spanstarter
      REDISHOST: redis
      REDISPORT: 6379
  redis:
    image: 'redis:3.2'
    ports:
      - 6379:6379
  mongo:
    image: 'mongo:3.4'
    ports:
      - 27017:27017